microsoft/cppgraphqlgen

- GraphQLService.cpp
- GraphQLTree.cpp
- GraphQLTree.h
- SchemaGenerator.cpp
- test_today.cpp
- tests.cpp
The `tao::pegtl::parse_tree` keeps pointers to the parsed input buffer instead of making deep copies. If the parse_tree outlives the buffer it parsed (e.g. the `file_input<>` is closed or the `std::string` is deleted or goes out of scope) the pointers inside of the `parse_tree` are all invalidated.
To fix this potential bug, I'm bundling the lifetimes of these two objects in a single template struct called `ast` which declares the input holder before the `parse_tree` holder so it's always destroyed last. This also preserves the input in case it's useful in the future, e.g. caching a query.
> Keep the parse_tree input alive so the string pointers remain valid

- GraphQLService.cpp
- GraphQLService.h
- SchemaGenerator.cpp
- Today.cpp
- Today.h
- samples/IntrospectionSchema.cpp
- samples/IntrospectionSchema.h
- samples/TodaySchema.cpp
- samples/TodaySchema.h
- tests.cpp
RapidJSON use a separate memory pool for each document, and if you want the lifetime of the values in the document to match you need to allocate them with the document's allocator. Since I was using separate documents for the resolvers, that meant every value had to be deep-copied into the final results. This branch makes it so the resolvers pass the allocator from the original document down and perform all of the allocations there and then insert them into the document without an additional call to `rapidjson::Value::CopyFrom`.
> Use a single rapidjson::Document and allocator for the entire result set

- CMakeLists.txt
When UPDATE_SAMPLES=ON and BUILD_TESTS=OFF,
the install target produced the following error:
-- Install configuration: ""
-- Installing: .../samples/IntrospectionSchema.h
-- Installing: .../samples/IntrospectionSchema.cpp
CMake Error at cmake_install.cmake:49 (file):
file INSTALL cannot find
".../TodaySchema.h".
The reason was that by default `add_custom_command()`
is not added to the default build target.
`add_custom_target(<tgt> ALL ...)` on the other hand has this capability,
so use that.
> CMake: fix TodaySchema sample install

- CMakeLists.txt
- GraphQLService.cpp
- GraphQLService.h
- Introspection.cpp
- Introspection.h
- SchemaGenerator.cpp
- Today.cpp
- Today.h
- samples/IntrospectionSchema.cpp
- samples/IntrospectionSchema.h
- samples/TodaySchema.cpp
- samples/TodaySchema.h
- test_today.cpp
- tests.cpp
Between using `std::future<>` and adding the `requestId` parameter for correlation, this should address the asynch and optimization suggestions from #11. The suggestion to abstract the results away from JSON is still pending.
> Use std::future<> to allow concurrency and batching in queries

- CMakeLists.txt
- GraphQLResponse.cpp
- GraphQLResponse.h
- GraphQLService.cpp
- GraphQLService.h
- GraphQLTree.cpp
- Introspection.cpp
- Introspection.h
- JSONResponse.cpp
- JSONResponse.h
- SchemaGenerator.cpp
- SchemaGenerator.h
- Today.cpp
- Today.h
- samples/IntrospectionSchema.cpp
- samples/IntrospectionSchema.h
- samples/TodaySchema.cpp
- samples/TodaySchema.h
- test_today.cpp
- tests.cpp
This should complete the suggestions in #11. Instead of taking a dependency on a specific JSON library and requiring JSON serialization, I'm building the GraphQL responses in a `response::Value` object that acts as a discriminated union of the primitive types supported in GraphQL.
It's still convenient to be able to serialize to and from JSON, particularly in the unit tests, so I also added a couple of conversion routines in `JSONResponse.h` which still use RapidJSON. The service library itself doesn't link against that though, so consumers are free to replace RapidJSON with the parser/generator of their choice when integrating it into another project. You could even skip using JSON entirely and pick another format that's compatible with GraphQL serialization.
> Refactor responses into a non-JSON type

- .gitignore
- GraphQLService.cpp
- Introspection.cpp
- SchemaGenerator.cpp
- Today.cpp
- include/Today.h
- include/graphqlservice/GraphQLService.h
- include/graphqlservice/Introspection.h
- samples/IntrospectionSchema.h
- samples/TodaySchema.h
- tests.cpp
There are a few places where we need to capture the `std::shared_ptr<service::RequestState>` and keep it alive in a member, a lambda capture, or `std::async` callback parameter, but most of the `service::Object::getField` accessors don't need to keep a copy of it. It's cheaper to go back to passing them by `const&` where possible.
> Switch back to passing const std::shared_ptr<service::RequestState>& where possible

- CMakeLists.txt
- JSONResponse.cpp
- include/graphqlservice/JSONResponse.h
- test_today.cpp
- tests.cpp
The serialization interface is pretty tiny (1 function/method in each direction), but the JSON library dependency is non-trivial. This refactor moves all of that dependency into a separate library so consumers can replace the JSON library as they see fit (e.g. they've already linked against something else and don't want to add RapidJSON to their project).
> Separate JSON serialization into its own library

- GraphQLResponse.cpp
- JSONResponse.cpp
- include/graphqlservice/GraphQLResponse.h
I ran the Code Analysis tool on VC++, and aside from a bunch of warnings in RapidJSON and GoogleTest it found some issues in this code. Specifically, I split the union of GraphQLResponse's _boolean, _int, and _float members so they could be default initialized.
> Fix VC++ Code Analysis and g++ warnings

- GraphQLService.cpp
- include/graphqlservice/GraphQLService.h
- tests.cpp
I added another override for `deliver` which takes an argument comparison callback. The previous override which takes a map of argument values for exact matching calls through to that and passes a callback which looks for an exact match with the value in the map.
> Support fuzzy subscription argument matching

- GraphQLTree.cpp
- include/GraphQLGrammar.h
PEGTL has a default control template class (`normal`) which raises `parse_error` exceptions using the type name of the required rule that was not matched. Some of the types in my GraphQL grammar were ambiguous and hard to map to the grammar rule that expected them.
I refactored the grammar to use a custom control template and I encapsulated all of the `must` or `if_must` rules which are the only valid match in those locations with `*_content` rules that can be unambiguously specialized in the control template class.
> Clean up graphqlpeg::parse_error exception messages

- GraphQLService.cpp
- SchemaGenerator.cpp
- include/graphqlservice/GraphQLService.h
- samples/IntrospectionSchema.cpp
- samples/TodaySchema.cpp
- tests.cpp
Instead of just throwing exceptions and bailing on the entire request, I'm propagating separate "data" and "errors" members up the response tree and translating any exceptions caught from a field resolver to an error message. In cases where an error occurs, callers should get partial results in "data" and all accumulated error messages in "errors." This resolves #28.
> Better exception/error handling

- GraphQLService.cpp
- include/graphqlservice/GraphQLService.h
Apollo may use a single websocket connection to perform queries, mutations, and subscriptions. To dispatch requests based on the operation type (particularly subscriptions which need to call subscribe instead of resolve), consumers need to be able to lookup the named (or unnamed when there's only one) operation in the query AST and get the operation type.
This also cuts down on a lot of code duplication between OperationDefinitionVisitor and SubscriptionDefinitionVisitor.
> Expose findOperationDefinition to fix #34

- SchemaGenerator.cpp
- include/SchemaGenerator.h
- samples/IntrospectionSchema.cpp
- samples/IntrospectionSchema.h
- samples/TodaySchema.cpp
- samples/TodaySchema.h
- samples/schema.today.graphql
- tests.cpp
> Generate NYI stubs for all of the field getters

- include/GraphQLGrammar.h
The PEGTL rules `plus<...>` and `opt<...>` are variadic with an implicit `seq<...>`, hence `opt<seq<...>>` can always be replaced with `opt<...>`, likewise for `plus<seq<...>>`.
> Simplify grammar

- .gitignore
This makes building in the source directory better, e.g. with default options from the CMake command line.
> Update gitignore to match the new directory structure

- include/graphqlservice/GraphQLService.h
- samples/CMakeLists.txt
- src/CMakeLists.txt
- test/CMakeLists.txt
I'm experimenting with building static libs in a CI/CD pipeline and consuming them with the headers in a separate project.
> Build tweaks to help with redistributable static libs

- samples/CMakeLists.txt
`MSBuild` and `Ninja` seem to handle creating the sub-directories under `CMAKE_CURRENT_BINARY_DIR` without explicitly creating them, but regular `make` does not. add a couple of lines to the `CMakeLists.txt` to create the directories there if they do not exist.
> Fix samples build with make and separate build dir

- src/SchemaGenerator.cpp
When parsing an `input` type as a parameter, the generator previously did not add the namespace, causing the name to not be resolved. This appears to fix that. Please let me know if there is some edge case where this breaks something.
> Fixed generator to correctly add the namespace for input types

- include/graphqlservice/GraphQLService.h
- samples/today/sample.cpp
- src/GraphQLResponse.cpp
- src/GraphQLService.cpp
This turned into a bigger change than I expected. While testing the input for the sample app, I tried a bunch of queries that threw `schema_exception` and eventually crashed. Part of the problem was that I deleted the copy constructor on schema_exception, but that's part of the interface for `std::exception` which is used by `std::exception_ptr`, and it ended up dropping the `_errors` member in the copy operation.
Once that was fixed, I noticed that higher levels were eating `schema_exception` along with `std::exception` and turning more specific error messages into "Unknown error" messages at that level of the query. I added `catch (schema_exception &)` blocks to each of those spots, and instead of turning it into a single generic error message it will either propagate the …
> Handle blank lines in the sample app and fix problems with schema_exception

- include/SchemaGenerator.h
- src/SchemaGenerator.cpp
Also replaces a few instance of
```cpp
sourceFile << R"cpp(
)cpp";
```
with
```cpp
sourceFile << std::endl;
```
for the sake of conciseness.
> Avoid adding extra blank lines between namespace starts

- samples/CMakeLists.txt
- src/CMakeLists.txt
There seems to be a dependency ordering issue on Windows with MSBuild where it's not generating the `IntrospectionSchema.*` files before it tries to update the samples, or maybe the relative paths are wrong.
This change separates the `update_samples` custom command/target into `update_samples` and `update_introspection`, so updating the `IntrospectionSchema.*` takes place in the same `src/CMakeLists.txt` and working directory as the code generator which creates them.
> Fix the CI build on Windows

- .gitignore
- CMakeLists.txt
- cmake/CMakeLists.txt
- samples/CMakeLists.txt
- src/CMakeLists.txt
I started building with Visual Studio on Windows Subsystem for Linux and found that when it tried to use CMake 3.10 which is the default on Ubuntu bionic, there were a few modern syntax options that didn't work, particularly with Unix Makefiles.
In particular, you can't link against an `OBJECT` library in CMake 3.10 (or 3.8.2, which is what I specified a long time ago in the `CMakeLists.txt` files). Switching to linking against the `TARGET_OBJECTS` and sorting out the `PUBLIC` include directories, dependencies, etc. was more complicated.
I also couldn't use `list(TRANSFORM ...)` to build the full paths to the generated schema files in one line, so I replaced that with a `foreach(... IN LISTS ...)` loop.
> CMake tweaks to be compatible with earlier versions

- samples/today/schema.today.graphql
Mostly I want to test the error recovery logic I added to the PR validation build in case it can't download pre-built vcpkg artifacts on Linux.
> Fix some inconsistent tabs in the sample schema

- src/Introspection.cpp
BUG: When I make an instrospection query with non-valid type name as parameter the program crashes.
I've see that the method 'Schema::LookupType' tries to find the name of
the type in the '_typeMap' map, but it assumes that always exists, and
this is not correct.
Result: Crash (Core dump).
Reproducible: Always.
O.S.: GNU/Linux (OpenSuse)
GCC version: 9.2.1
schema.graphql
```
schema {
query: Query
}
"My description"
type Query {
myData: String
}
```
valid_query_file.graphql
```
{
__type(name: "Query") {
description
}
}
```
crash_query_file.graphql
```
{
__type(name: "Other") {
description
}
}
```
> BUG: Instrospection query with non-valid type name crashes

- src/CMakeLists.txt
Updating `vcpkg` to the v3.1.0 release uncovered a dependency in CMake on Windows. Generating the `IntrospectionSchema.*` files as part of the build depends on `schemagen`, and when `vcpkg` builds it it hasn't run `appLocal.ps1` to copy the runtime dependencies for `schemagen` to the build directory yet. So `schemagen.exe` fails to load `boost-program-options.dll` and breaks the build.
Workaround is to just copy the latest version of `IntrospectionSchema.*` from the `samples` directory to the build directory if `GRAPHQL_UPDATE_SAMPLES` is turned off, as it is in the `vcpkg` build.
> CMake fixes to skip regenerating IntrospectionSchema.* in vcpkg

- README.md
- doc/parsing.md
- doc/resolvers.md
- doc/subscriptions.md
- samples/introspection/IntrospectionSchema.cpp
- src/GraphQLTree.cpp
- src/SchemaGenerator.cpp
* Some of the docs are out of date with v3.1.0.
* The `defaultValue` property in Introspection should be a GraphQL input value encoded as a string. It was decoding GraphQL strings and putting the encoded string in there as part of SchemaGenerator. It worked OK until I tested it with Graph*i*QL. It was trying to parse that value as a string for the `@deprecated(reason: String = "No longer supported")` argument default value.
> Doc updates and a bug fix for defaultValue in Introspection

- CMakeLists.txt
- include/graphqlservice/GraphQLParse.h
- include/graphqlservice/GraphQLResponse.h
- include/graphqlservice/GraphQLService.h
- include/graphqlservice/Introspection.h
- include/graphqlservice/JSONResponse.h
- samples/CMakeLists.txt
- samples/introspection/IntrospectionSchema.h
- src/CMakeLists.txt
- src/GraphQLService.cpp
- src/SchemaGenerator.cpp
- test/CMakeLists.txt
If you used `BUILD_SHARED_LIBS` on Windows (including building with `vcpkg` by default), it was setting `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` and letting `CMake` figure out all of the symbols in all of the DLLs and mark them as exported. That bloats the import libs which are used to consume them and increases the binary size considerably.
This PR undoes that and replaces it with explicit `__declspec(dllimport/dllimport)` attributes defined conditionally through macros on Windows for the methods which are actually referenced across modules.
> Use explicit DLL exports on Windows

- .clang-format
- include/graphqlservice/GraphQLGrammar.h
- samples/schema.today.graphql
- samples/separate/TodaySchema.cpp
- samples/unified/TodaySchema.cpp
The clang-format configuration doesn't produce exactly the same style I prefer, but the differences are acceptable IMO. I tested it on a Mac with VS Code and apple-clang 11.
> Bug fix and initial clang-format config

- README.md
If one wants to build the project without using a build dir, it will
fail. Thus, adding the instructions to warn about it on Command Line
instructions section.
Also, improved the documentation on how to configure cmake to use
Release configuration and install public outputs.
Closes #102
> docs: update README.md with build dir instructions

- include/graphqlservice/GraphQLService.h
- samples/today/TodayMock.h
- src/GraphQLService.cpp
- test/TodayTests.cpp
Fix #116 
I added overloads to `Request::subscribe` and `Request::unsubscribe` which take a `std::async` launch policy and return a `std::future<>`. If you use these overrides to subscribe and unsubscribe, and you provided a default `Subscription` operation implementation, then as a side effect of asynchronously adding or removing the subscription callback it will also resolve the subscription against the default operation and pass `params.resolverContext` with `ResolverContext::NotifySubscribe` or `ResolverContext::NotifyUnsubscribe`. The result of the resolver will be ignored, but exceptions will rethrow and should not alter the registration.
You can also use these overrides without a default `Subscription` operation implementation, but in that case all it does is make the …
> Notify on subscribe

- include/graphqlservice/GraphQLGrammar.h
- include/graphqlservice/GraphQLResponse.h
- samples/schema.today.graphql
- samples/separate/MutationObject.cpp
- samples/separate/MutationObject.h
- samples/today/TodayMock.cpp
- samples/today/TodayMock.h
- samples/unified/TodaySchema.cpp
- samples/unified/TodaySchema.h
- src/GraphQLResponse.cpp
- src/GraphQLService.cpp
- test/TodayTests.cpp
Fix #120 
There were two bugs reported in this issue, the first is that whole numbers (`IntValue`) don't get coerced to floats (`FloatValue`). I added coercion handling to `ModifiedArgument` and `response::Value::get`/`set` to treat integers as valid inputs and automatically `static_cast` them to `FloatType` if that is the expected type. I added a unit test for this case. 
The second was that the grammar doesn't parse float input values. It rejects them as malformed integers. I swapped the order that `input_value_content` matches them so that the more specific `float_value` is tested first, and I added a unit test for this as well.
> Float input values

- include/graphqlservice/GraphQLService.h
- test/ArgumentTests.cpp
`ModifiedArgument<T>::require<>` works without any default arguments, but `ModifiedArgument<T>::find<>` does not. This change adds a default `TypeModifier::None` template argument to the method declaration which gets forwarded to `require<>`.
> Add a default template argument to ModifiedArgument<T>::find<...>

- README.md
- src/CMakeLists.txt
- src/SchemaGenerator.cpp
Sync to the 3.0.0 tag on the `PEGTL` submodule and update all of the `std::filesystem` dependencies/docs to remove the `boost-filesystem` fallback now that `PEGTL` depends on `std::filesystem`. That means I also bumped the Linux compiler versions up in the "tested with" section, it may work with a lower version number of either `gcc` or `clang`, but I haven't tried to find a lower version number than the latest LTS versions.
> Update to PEGTL 3.0.0 Release

- CMakeLists.txt
- README.md
- cmake/test_filesystem.cpp.in
- include/Validation.h
- include/graphqlservice/GraphQLService.h
- src/CMakeLists.txt
- src/GraphQLService.cpp
- src/SchemaGenerator.cpp
- src/Validation.cpp
After figuring out how to auto-detect `std::filesystem` support in PEGTL, I ported some of that CMake logic to this project. Now that they both have this capability, I can resume updating the vcpkg ports.
> Re-add the Boost.Filesystem fallback

- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
- CMakeLists.txt
- include/graphqlservice/GraphQLSchema.h
- include/graphqlservice/GraphQLTree.h
- samples/CMakeLists.txt
- src/GraphQLSchema.cpp
- test/CMakeLists.txt
Build Windows, Linux, and macOS workflows to build cppgraphqlgen and run all of the unit tests. Dependencies are cached so subsequent runs should be faster.
> Add GitHub Actions workflows for CI and PR validation

- CMakeLists.txt
- include/graphqlservice/GraphQLTree.h
- src/CMakeLists.txt
PEGTL has a [fix](https://github.com/taocpp/PEGTL/commit/0cc3128e07734fb72e23e2eeee70b9f1fc13ca5f) for the namespace of `::tao::demangle` pending for the 3.1.1 release, but the most recent release is still 3.1.0.  That makes upgrading `cppgraphqlgen` to its most recent releases complicated, so I'm adding a fallback which re-declares `demangle` in the `tao::graphqlpeg` namespace used by `cppgraphqlgen` (defined with `TAO_PEGTL_NAMESPACE`) if the PEGTL version is < 3.1.1.
I introduced #151 with #150 when I missed a couple of global replacements that switched the install target for some of the include files to `graphqlintrospection/...`. This changes those back to `graphqlservice/...` in the `CMakeLists.txt` file, so install should put them in the right place.
> Add backwards compatibility with PEGTL 3.1.0 and fix the header install paths

- include/graphqlservice/GraphQLSchema.h
fixes build error:
```
graphqlservice/GraphQLSchema.h:126:7: error: base class 'class graphql::schema::BaseType' has accessible non-virtual destructor [-Werror=non-virtual-dtor]
```
> add virtual dtor

- include/graphqlservice/GraphQLService.h
_listeners used a string_view as key, it would point to the first
registration->field value, but once that value is gone, the reference
will point to garbage and the process will crash.
Change it to a string, the copy is harmless given the other costs of
subscription.
Closes: #162
> Fix subscription listeners key

- include/graphqlservice/GraphQLResponse.h
- include/graphqlservice/GraphQLService.h
- samples/today/TodayMock.cpp
- samples/today/TodayMock.h
- src/GraphQLResponse.cpp
- src/GraphQLService.cpp
In cases where copying elements between `service::ResolverResult` documents and converting to `response::Value` adds a lot of overhead, field getters can now hold on to a pre-converted `std::shared_ptr<const response::Value>` and return that. The `ModifiedResult` and `FieldResult` will prefer that over a value of `T` or `std::future<T>`, and `response::Value` can now perform copy-on-write from a `std::shared_ptr<const response::Value>`, so it doesn't need to repeat any conversion or copying to keep returning the same `shared_ptr`.
> Allow field getters to return a std::shared_ptr<const response::Value>

- samples/client/benchmark.cpp
- samples/today/TodayMock.cpp
- samples/today/TodayMock.h
- samples/today/benchmark.cpp
- samples/today/sample.cpp
- test/ClientTests.cpp
- test/NoIntrospectionTests.cpp
- test/TodayTests.cpp
There's a lot of nearly duplicate code for setting up a TodayMock service for use in benchmarks, samples, and tests, so I centralized that in a factory function and struct in TodayMock itself.
I also put a mutex around each of the loader callbacks, so when resolve is handling multiple fields in parallel there isn't a race condition which loads more than once or fails to update the loading count in the callback. Combined with resetting the test state for each test method, this should fix the lingering intermittent failures.
> Consolidate TodayMock services and protect async loaders with mutex

- samples/client/mutate/MutateClient.cpp
- samples/client/mutate/MutateClient.h
- samples/client/mutate/mutate.today.graphql
- src/ClientGenerator.cpp
> Don't add Variables:: scope to scalar and built-in types in clientgen

- .github/workflows/windows.yml
- README.md
Recent versions of MSVC trigger a `static_assert` in 3.2.2 which was fixed in a patch release of PEGTL.
> Update PEGTL submodule to 3.2.5

- include/graphqlservice/GraphQLService.h
Adds a default destructor to allow the use of `std::dynamic_pointer_cast` on a RequestState derivation
> Adds a virtual default destructor for RequestState

- CMakeLists.txt
- src/CMakeLists.txt
- src/GraphQLResponse.cpp
- src/Validation.cpp
This one is a bit of a bigger one - we've been looking at other GQL implementations in other languages, and noticed that they don't encode Base64 for the ID type. 
While I agree that Base64 IDs are actually better given their implicit binary nature - we need to get consistency between the other implementations we are building up. 
Given the scope of changes and breakage for existing client usage - I've added an option as a compile time flag for the behaviour change. 
Obviously - the library user would need to ensure that they are not encoding anything that is illegal here - but given its an opt-in - I would expect its more a "user-beware" sort of option
> Options to remove base64 ID encoding at compile time

- samples/proxy/client.cpp
- samples/proxy/query/ProxyClient.cpp
- samples/proxy/query/ProxyClient.h
- samples/proxy/schema/QueryObject.cpp
- samples/proxy/schema/QueryObject.h
- samples/proxy/schema/schema.graphql
- src/GraphQLService.cpp
I tried running the `client` HTTP sample without starting the `server`, and I noticed that the `Boost.Beast` error from failing to connect was not being handled gracefully.
In the process of adding error reporting to the `client`, I realized that exceptions thrown from awaitable resolvers are caught in the `Object::resolve` method instead of the `SelectionVisitor::visitField` method, and they are missing the field location and path information. We only report the error message.
> Improve awaitable errors

- .github/workflows/macos.yml
- .github/workflows/windows.yml
The macos and windows PR/CI pipelines are not properly caching the dependencies automatically installed with `vcpkg`. Setting the `VCPKG_BINARY_SOURCES` environment variable seems to fix it.
> Make workflows work with vcpkg binary artifact caching

- src/GraphQLResponse.cpp
I haven't been able to reproduce the same build break locally, but this ought to fix the error that was reported in #301.
> Attempt to fix Linux build

- samples/learn/schema/StarWarsSchema.cpp
- samples/learn/schema/StarWarsSchema.h
- samples/today/nointrospection/TodaySchema.cpp
- samples/today/nointrospection/TodaySchema.h
- samples/today/schema/TodaySchema.cpp
- samples/today/schema/TodaySchema.h
- samples/validation/schema/ValidationSchema.cpp
- samples/validation/schema/ValidationSchema.h
- src/SchemaGenerator.cpp
The same issue exists in the schema input types as in the client input types, although I never actually saw that with any of the schema samples.
The error I saw once with clang 14 on an `Ubuntu 22.04` derived image (`Pop OS!`, specifically) had to do with not having a constructor for nested input type members available in the header when compiling the default member initializers using `{}` at the end of the member declaration. Since we've already pulled the default constructor for the type itself into the source file to fix ODR violations, it makes sense to move the default member initialization into the constructor's initializer list.
> fix: schema input type member default init error on clang 14

- include/graphqlservice/GraphQLClient.h
- include/graphqlservice/GraphQLService.h
- samples/client/multiple/MultipleQueriesClient.cpp
- samples/client/multiple/MultipleQueriesClient.h
- samples/client/mutate/MutateClient.cpp
- samples/client/mutate/MutateClient.h
- samples/today/schema.today.graphql
- test/ClientTests.cpp
When input has type: [Boolean!] the compilation [fails ](https://github.com/gitmodimo/cppgraphqlgen/actions/runs/11955767049/job/33328910606). 
This PR adds special handling of std::vector<bool>.
> Fix boolean list input

- samples/CMakeLists.txt
- samples/client/query/QueryClient.cpp
- samples/client/query/QueryClient.h
- samples/client/query/query.today.graphql
- samples/proxy/query/ProxyClient.cpp
- samples/today/CMakeLists.txt
- samples/today/TodayMock.cpp
- samples/today/TodayMock.h
- samples/today/nointrospection/AppointmentObject.cpp
- samples/today/nointrospection/TodayAppointmentObject.h
- samples/today/schema.today.graphql
- samples/today/schema/AppointmentObject.cpp
- samples/today/schema/TodayAppointmentObject.h
- src/ClientGenerator.cpp
> Merge latest changes/fixes in next branch
